# Generated by Django 5.1.6 on 2025-04-05 05:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matapelajaran', '0001_initial'),
        ('tahunajaran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('angkatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tahunajaran.angkatan')),
                ('tier1_option1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t1o1', to='matapelajaran.matapelajaran')),
                ('tier1_option2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t1o2', to='matapelajaran.matapelajaran')),
                ('tier2_option1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t2o1', to='matapelajaran.matapelajaran')),
                ('tier2_option2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t2o2', to='matapelajaran.matapelajaran')),
                ('tier3_option1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t3o1', to='matapelajaran.matapelajaran')),
                ('tier3_option2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t3o2', to='matapelajaran.matapelajaran')),
                ('tier4_option1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t4o1', to='matapelajaran.matapelajaran')),
                ('tier4_option2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='t4o2', to='matapelajaran.matapelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='PilihanSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier1', models.BooleanField(blank=True, null=True)),
                ('tier2', models.BooleanField(blank=True, null=True)),
                ('tier3', models.BooleanField(blank=True, null=True)),
                ('tier4', models.BooleanField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Linimasa', to='pengajuan_peminatan.event')),
            ],
        ),
    ]
