# Generated by Django 5.1.6 on 2025-04-24 03:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaKelas', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('angkatan', models.IntegerField(default=2023)),
                ('kode', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('kode_expiry_time', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('expiredAt', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
