# Generated by Django 5.1.6 on 2025-03-18 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kelas', '0001_initial'),
        ('tahunajaran', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='siswa',
            field=models.ManyToManyField(related_name='siswa', to='user.student'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='tahunAjaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tahunajaran.tahunajaran'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='waliKelas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waliKelas', to='user.teacher'),
        ),
    ]
