# Generated by Django 5.1.6 on 2025-03-08 07:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0001_initial'),
        ('tahunajaran', '0001_initial'),
        ('user', '0005_rename_homeroom_id_teacher_homeroomid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='siswa',
            field=models.ManyToManyField(related_name='siswa', to='user.student'),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='tahunAjaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tahunajaran.tahunajaran'),
        ),
    ]
