# Generated by Django 5.1.6 on 2025-03-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0001_initial'),
        ('user', '0004_student_name_student_username_teacher_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='siswa',
            field=models.ManyToManyField(related_name='siswa', to='user.student'),
        ),
    ]
