# Generated by Django 5.1.6 on 2025-03-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelas',
            name='isActive',
        ),
        migrations.AddField(
            model_name='kelas',
            name='expiredAt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
