# Generated by Django 5.1.6 on 2025-03-13 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0002_initial'),
        ('tahunajaran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='tahunAjaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tahunajaran.tahunajaran'),
        ),
    ]
