# Generated by Django 5.1.6 on 2025-03-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0003_remove_kelas_isactive_kelas_expiredat'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
