# Generated by Django 5.1.6 on 2025-03-13 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0003_alter_kelas_tahunajaran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelas',
            name='tahunAjaran',
        ),
    ]
