# Generated by Django 5.1.6 on 2025-03-13 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0004_remove_kelas_tahunajaran'),
        ('tahunajaran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='tahunAjaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tahunajaran.tahunajaran'),
        ),
    ]
