# Generated by Django 5.1.6 on 2025-03-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0004_kelas_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
