# Generated by Django 5.1.6 on 2025-03-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0005_kelas_tahunajaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='angkatan',
            field=models.IntegerField(default=2023),
        ),
    ]
