# Generated by Django 5.1.6 on 2025-04-09 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('komponenpenilaian', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tipe_nilai', models.CharField(choices=[('pengetahuan', 'Pengetahuan'), ('keterampilan', 'Keterampilan')], default='pengetahuan', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('komponen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nilai_records', to='komponenpenilaian.komponenpenilaian')),
            ],
            options={
                'ordering': ['student', 'komponen', 'tipe_nilai'],
            },
        ),
    ]
