# Generated by Django 5.1.6 on 2025-05-20 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('komponenpenilaian', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('komponen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nilai_records', to='komponenpenilaian.komponenpenilaian')),
            ],
            options={
                'ordering': ['student', 'komponen'],
            },
        ),
    ]
