# Generated by Django 5.1.6 on 2025-04-05 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komponenpenilaian', '0002_alter_komponenpenilaian_namakomponen_and_more'),
        ('nilai', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nilai',
            options={'ordering': ['student', 'komponen']},
        ),
        migrations.AlterUniqueTogether(
            name='nilai',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='nilai',
            name='komponen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nilai_siswa', to='komponenpenilaian.komponenpenilaian'),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='nilai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_komponen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='nilai',
            name='keterangan',
        ),
        migrations.RemoveField(
            model_name='nilai',
            name='matapelajaran',
        ),
    ]
