# Generated by Django 5.1.6 on 2025-04-05 23:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('komponenpenilaian', '0002_alter_komponenpenilaian_namakomponen_and_more'),
        ('nilai', '0003_alter_nilai_options_alter_nilai_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nilai',
            unique_together={('student', 'komponen')},
        ),
    ]
