# Generated by Django 5.1.6 on 2025-04-08 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komponenpenilaian', '0002_alter_komponenpenilaian_namakomponen_and_more'),
        ('nilai', '0004_alter_nilai_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nilai',
            options={'ordering': ['student', 'komponen', 'tipe_nilai']},
        ),
        migrations.AlterUniqueTogether(
            name='nilai',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='nilai',
            name='tipe_nilai',
            field=models.CharField(choices=[('pengetahuan', 'Pengetahuan'), ('keterampilan', 'Keterampilan')], default='pengetahuan', max_length=15),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='komponen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nilai_records', to='komponenpenilaian.komponenpenilaian'),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_siswa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='nilai',
            unique_together={('student', 'komponen', 'tipe_nilai')},
        ),
    ]
