# Generated by Django 5.1.6 on 2025-03-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angkatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angkatan', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahunAjaran', models.IntegerField(default=2025, unique=True)),
            ],
        ),
    ]
