# Generated by Django 5.1.6 on 2025-03-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahunajaran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tahunajaran',
            name='tahunAjaran',
            field=models.IntegerField(default=2025, unique=True),
        ),
    ]
