# Generated by Django 5.1.6 on 2025-05-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapaianKompetensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('Pengetahuan', 'Pengetahuan'), ('Keterampilan', 'Keterampilan')], max_length=20)),
                ('deskripsi', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['mata_pelajaran', 'tipe'],
            },
        ),
    ]
