# Generated by Django 5.1.6 on 2025-05-19 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capaiankompetensi', '0001_initial'),
        ('matapelajaran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capaiankompetensi',
            name='mata_pelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capaian_kompetensi', to='matapelajaran.matapelajaran'),
        ),
        migrations.AlterUniqueTogether(
            name='capaiankompetensi',
            unique_together={('mata_pelajaran', 'tipe')},
        ),
    ]
