services:
  backend:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      SECRET_KEY: "bangabb"
      DEBUG: "False"