services:
  backend:
    build: .
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    restart: always
    command: celery -A your_project worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
