version: '3.8'

services:
  backend:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      SECRET_KEY: "bangabb"
      DEBUG: "False"
      CELERY_BROKER_URL: "redis://redis:6379/0"  # Use Redis as the Celery broker
    depends_on:
      - redis
      - celery

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    restart: always
    command: celery -A your_project worker --loglevel=info
    depends_on:
      - redis
      - backend
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
