# Generated by Django 5.1.6 on 2025-03-17 14:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tahunajaran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.TextField(max_length=100)),
                ('kategoriMatpel', models.CharField(choices=[('BING_WAJIB', 'Bahasa Inggris Wajib'), ('BING_PEMINATAN', 'Bahasa Inggris Peminatan'), ('MTK_WAJIB', 'Matematika Wajib'), ('MTK_PEMINATAN', 'Matematika Peminatan'), ('FISIKA', 'Fisika'), ('KIMIA', 'Kimia'), ('BIOLOGI', 'Biologi')], max_length=50)),
                ('kode', models.CharField(blank=True, max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('angkatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tahunajaran.angkatan')),
            ],
        ),
    ]
