# Generated by Django 5.1.6 on 2025-03-17 16:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tahunajaran', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(default='Default Subject', max_length=100)),
                ('kategoriMatpel', models.CharField(choices=[('Wajib', 'Wajib'), ('Peminatan', 'Peminatan')], default='Wajib', max_length=10)),
                ('kode', models.CharField(blank=True, max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('angkatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tahunajaran.angkatan')),
                ('siswa_terdaftar', models.ManyToManyField(blank=True, related_name='matapelajaran_diikuti', to='user.student')),
                ('tahunAjaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tahunajaran.tahunajaran')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matapelajaran_diajarkan', to='user.teacher')),
            ],
        ),
    ]
