# Generated by Django 5.1.6 on 2025-04-23 15:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tahunajaran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='Default Subject', max_length=100)),
                ('kategoriMatpel', models.CharField(choices=[('Wajib', 'Wajib'), ('Peminatan', 'Peminatan')], default='Wajib', max_length=10)),
                ('kode', models.CharField(blank=True, max_length=20)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('expiredAt', models.DateField(blank=True, null=True)),
                ('angkatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tahunajaran.angkatan')),
            ],
        ),
    ]
