# Generated by Django 5.1.6 on 2025-03-07 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matapelajaran', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matapelajaran',
            unique_together={('namaMatpel', 'kelas', 'tahun_ajaran')},
        ),
    ]
