# Generated by Django 5.1.6 on 2025-04-05 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matapelajaran', '0001_initial'),
        ('tahunajaran', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matapelajaran',
            name='siswa_terdaftar',
            field=models.ManyToManyField(blank=True, related_name='matapelajaran_diikuti', to='user.student'),
        ),
        migrations.AddField(
            model_name='matapelajaran',
            name='tahunAjaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tahunajaran.tahunajaran'),
        ),
        migrations.AddField(
            model_name='matapelajaran',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matapelajaran_diajarkan', to='user.teacher'),
        ),
    ]
