# Generated by Django 5.1.6 on 2025-03-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matapelajaran', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matapelajaran',
            name='nama',
        ),
        migrations.AddField(
            model_name='matapelajaran',
            name='angkatan',
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='matapelajaran',
            name='namaMatpel',
            field=models.CharField(default='Default Subject', max_length=100),
        ),
        migrations.AlterField(
            model_name='matapelajaran',
            name='kategoriMatpel',
            field=models.CharField(choices=[('Wajib', 'Wajib'), ('Peminatan', 'Peminatan')], default='Wajib', max_length=10),
        ),
    ]
