# Generated by Django 5.1.6 on 2025-03-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matapelajaran', '0003_remove_matapelajaran_nama_matapelajaran_angkatan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matapelajaran',
            old_name='namaMatpel',
            new_name='nama',
        ),
    ]
