# Generated by Django 5.1.6 on 2025-03-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tahun_ajaran',
            field=models.PositiveIntegerField(default=2024),
            preserve_default=False,
        ),
    ]
