# Generated by Django 5.1.6 on 2025-03-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_teacher_homeroomid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isAssignedtoClass',
            field=models.BooleanField(default=False),
        ),
    ]
