# Generated by Django 5.1.6 on 2025-03-08 07:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahunajaran', '0001_initial'),
        ('user', '0004_student_name_student_username_teacher_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='homeroom_id',
            new_name='homeroomId',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tahun_ajaran',
        ),
        migrations.AddField(
            model_name='student',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='tahunAjaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tahunajaran.tahunajaran'),
        ),
        migrations.AddField(
            model_name='student',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teacher',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
