# Generated by Django 5.1.6 on 2025-05-17 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matapelajaran', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variabel', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('indikator', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('skorlikert', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evalguru_guru', to='user.teacher')),
                ('matapelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evalguru_matapelajaran', to='matapelajaran.matapelajaran')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evalguru_siswa', to='user.student')),
            ],
        ),
    ]