# Generated by Django 5.1.6 on 2025-05-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalguru', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalguru',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
