# Generated by Django 5.1.6 on 2025-05-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalguru', '0002_alter_evalguru_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evalguru',
            name='kritik_saran',
            field=models.TextField(blank=True, null=True),
        ),
    ]