# Generated by Django 5.1.6 on 2025-05-20 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalguru', '0003_evalguru_kritik_saran'),
        ('matapelajaran', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalguru',
            name='indikator',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)]),
        ),
        migrations.AlterField(
            model_name='evalguru',
            name='variabel',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
        migrations.CreateModel(
            name='isianEvalGuru',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isian', models.JSONField(default=dict)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('kritik_saran', models.TextField(blank=True, null=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isianEvalGuru_guru', to='user.teacher')),
                ('matapelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isianEvalGuru_matapelajaran', to='matapelajaran.matapelajaran')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isianEvalGuru_siswa', to='user.student')),
            ],
        ),
    ]
