# Generated by Django 5.1.6 on 2025-05-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalguru', '0003_evalguru_kritik_saran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalguru',
            name='indikator',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)]),
        ),
        migrations.AlterField(
            model_name='evalguru',
            name='variabel',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
