# Generated by Django 5.1.6 on 2025-05-19 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evalguru', '0004_alter_evalguru_indikator_alter_evalguru_variabel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvalGuru',
        ),
    ]
