# Generated by Django 5.1.6 on 2025-05-21 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evalguru', '0005_delete_evalguru'),
        ('matapelajaran', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalGuru',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variabel', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('indikator', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('skorlikert', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('kritik_saran', models.TextField(blank=True, null=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evalguru_guru', to='user.teacher')),
                ('matapelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evalguru_matapelajaran', to='matapelajaran.matapelajaran')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evalguru_siswa', to='user.student')),
            ],
        ),
    ]
