# Generated by Django 5.1.6 on 2025-04-05 09:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matapelajaran', '0002_initial'),
        ('nilai', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KomponenPenilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaKomponen', models.CharField(max_length=100, unique=True)),
                ('bobotKomponen', models.IntegerField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('mataPelajaran', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='komponenpenilaian_matpel', to='matapelajaran.matapelajaran')),
                ('nilai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='komponenpenilaian_nilai', to='nilai.nilai')),
            ],
        ),
    ]
