# Generated by Django 5.1.6 on 2025-04-09 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KomponenPenilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaKomponen', models.CharField(max_length=100)),
                ('bobotKomponen', models.IntegerField()),
                ('tipeKomponen', models.CharField(max_length=15)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
