# Generated by Django 5.1.6 on 2025-05-19 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('komponenpenilaian', '0001_initial'),
        ('matapelajaran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='komponenpenilaian',
            name='mataPelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komponenpenilaian_matpel', to='matapelajaran.matapelajaran'),
        ),
        migrations.AlterUniqueTogether(
            name='komponenpenilaian',
            unique_together={('namaKomponen', 'mataPelajaran', 'tipeKomponen')},
        ),
    ]
