# Generated by Django 5.1.6 on 2025-04-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komponenpenilaian', '0001_initial'),
        ('matapelajaran', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komponenpenilaian',
            name='namaKomponen',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='komponenpenilaian',
            unique_together={('namaKomponen', 'mataPelajaran')},
        ),
    ]
