# Generated by Django 5.1.6 on 2025-04-09 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('komponenpenilaian', '0001_initial'),
        ('matapelajaran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='komponenpenilaian',
            name='mataPelajaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='komponenpenilaian_matpel', to='matapelajaran.matapelajaran'),
        ),
    ]
