# Generated by Django 5.1.6 on 2025-04-09 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('komponenpenilaian', '0002_initial'),
        ('nilai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='komponenpenilaian',
            name='nilai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='komponenpenilaian_nilai', to='nilai.nilai'),
        ),
        migrations.AlterUniqueTogether(
            name='komponenpenilaian',
            unique_together={('namaKomponen', 'mataPelajaran')},
        ),
    ]
