# Generated by Django 5.1.6 on 2025-03-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsensiHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=6, unique=True)),
                ('date', models.DateField()),
                ('listSiswa', models.JSONField(default=dict)),
                ('tipeAbsensi', models.CharField(choices=[('Hadir', 'Hadir'), ('Absen', 'Absen'), ('Izin', 'Izin'), ('Alfa', 'Alfa')], max_length=100)),
            ],
        ),
    ]
