# Generated by Django 5.1.6 on 2025-03-28 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absensi', '0001_initial'),
        ('kelas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absensiharian',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absen_kelas', to='kelas.kelas'),
        ),
    ]
