# Generated by Django 5.0.14 on 2025-06-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absensiharian',
            name='kode',
            field=models.CharField(max_length=8, null=True, unique=True, verbose_name='kel'),
        ),
    ]
