name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "Django>=4.2,<5.0"  # Install the latest stable Django 4.2.x
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd propeng-be  # Change directory to the project folder
        python manage.py test

    - name: Altostra Push and Deploy
      uses: altostra/push-deploy-action@v1.0.0
      with:
        env-name: "production"  # Change to your environment name (e.g., staging, dev, prod)
        instance-name: "my-instance"  # Change this to your Altostra instance name
        image-name: "latest"  # Optional: specify an image version if needed
