name: Django CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Modify Django Version in requirements.txt (if present)
      run: |
        if grep -i '^django' requirements.txt; then
          sed -i 's/^django.*/Django>=4.2,<5.0/' requirements.txt
        fi

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # manually not include django casue im dumb


    - name: Run Tests
      run: |
        cd propeng-be
        python manage.py test
